[platformio]
default_envs = production

[env:production]
platform = espressif32@6.7.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_speed = 115200
upload_flags =
  --no-stub
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCOMPETITION_HARDWARE_ENABLE=1
lib_deps =
  m5stack/M5Unified
